apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.azure.tablestorage
  metadata:
  - name: accountName
    value: daprstorage
  - name: accountKey
    value: <your-account-key>
  - name: tableName
    value: leaderboardstate
  - name: actorStateStore
    value: "false"
